### ISSUE TITLE
Task: Update user authentication documentation

### ISSUE THREAD

**Issue by eligigante** [eligigante/compiled-scheme-programs#6]
We've recently made some changes to our user authentication process, and it's time to ensure our documentation is up to date. The task is to review and update the relevant sections of the documentation to reflect the latest changes in the authentication flow. Let's collaborate on this task to keep our documentation accurate and helpful. Your contributions are much appreciated!

@amzapanta Please ensure that the documentation is up-to-date
@DianaCarino Write the specifics and the flow of the user-authentication
@HansDaligdig Proofread the documentation after the specifics are included

**Comment by SLU-Dominic** [comment]
sampleee
